testArray: test-array.cpp
	g++ -std=c++11 -O3 test-array.cpp -o array.out
	./array.out
testQueue: test-queue.cpp
	g++ -std=c++11 -O3 test-queue.cpp -o queue.out
	./queue.out
testMap: test-map.cpp
	g++ -std=c++11 -O3 test-map.cpp -o map.out
	./map.out
clean:
	rm *.out
